apiVersion: 1

datasources:
  - name: Redis
    type: redis-datasource
    uid: redis
    access: proxy
    url: fleet-redis:6379
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    secureJsonData:
      password: redis123
    editable: false
    isDefault: false

  - name: MongoDB
    type: grafana-mongodb-datasource
    uid: mongodb
    access: proxy
    url: mongodb://admin:admin123@fleet-mongodb:27017
    jsonData:
      authType: credentials
      tlsSkipVerify: true
    editable: false
    isDefault: false